### ISSUE TITLE
Can this tool ideally be flexible to record apache web latency from server access log?

### ISSUE THREAD

**Issue by boonchu** [toni-moreno/collectd-apachelog-plugin#3]

**Comment by toni-moreno** [comment]
This  collectd plugin can parse apache access.log files and look for HTTP CODE and response time if %D properly configured . ( RESPONSE TIME) 

Sorry but for me the concept of "Latency" is different than response time, and In this case: This collectd plugin can help you to measure Latency. 

you can see this link to get Latency:  http://digwp.com/2012/04/measure-latency-apache-bench/
